### ISSUE TITLE
NOT A ISSUE, JUST A QUESTION

### ISSUE THREAD

**Issue by Nottinghster** [SaiyansKing/Tibia-Outfit-Limit-Changer#1]
Hello SaiyansKing!

First of all, thank you for this amazing work :)

Now the question is:

Is possible to modify the client 8.6 to read .dat and .spr for Tibia 10.x+ ??? (For example, version 10.77)

Since the structure of newer versions are 4 bytes and have more flags (market and other things)
There's a possibility to read that kind of structure and remove those flags ?

**Comment by SaiyansKing** [comment]
Yes, it is possible to modify client that way, it is even possible to add the new animations system, store, imbuings, reward, cyclopedia etc.
But you probably will be unsatisfied with this answer because you probably want to know how to modify client/if I write code that does it, so no I'll not write code/tutorial for it because it'll take much of my time which I don't have for these things.
